### ISSUE TITLE
interested in permissions to test the onchain theming

### ISSUE THREAD

**Issue by mmsaki** [salieflewis/onchain-theming#18]
@salieflewis Just saw your on-chain theming project on your [twitter post](https://twitter.com/salieflewis/status/1632781250527125505). It's super dope! I want to try it out!

**Comment by salieflewis** [comment]
Thanks @mmsaki, what is your goerli address?

**Comment by mmsaki** [comment]
> Thanks @mmsaki, what is your goerli address?

0xFE948CB2122FDD87bAf43dCe8aFa254B1242c199

**Comment by salieflewis** [comment]
You've been added! Basically now you have permissions to update the theming on the site! Connect your wallet, mess with the theme, and hit save changes!
