### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by mmsaki** [salieflewis/onchain-theming#19]
Hey @salieflewis looks like there's Application error? 
<img width="1427" alt="Screenshot 2023-03-08 at 6 18 35 PM" src="https://user-images.githubusercontent.com/98189596/223882787-82a684d5-ea91-49b2-b4e7-546c7e958562.png">

**Comment by salieflewis** [comment]
That's so embarrassing. It's cause I'm using the same theming contract for this app and the flexible stuff. Will ping you when it is fixed. Gonna delete the deploy for now.
